apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deliveryrisk-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/237y1a0579-art/deliveryrisk-mlops.git
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: deliveryrisk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

