resources:
- ../../base
namespace: deliveryrisk
images:
- name: ghcr.io/OWNER/REPO/api
  newName: ghcr.io/237y1a0579-art/deliveryrisk-mlops/api
  newTag: model-13
- name: ghcr.io/OWNER/REPO/frontend
  newName: ghcr.io/237y1a0579-art/deliveryrisk-mlops/frontend
  newTag: latest
- name: ghcr.io/OWNER/REPO/drift
  newName: ghcr.io/237y1a0579-art/deliveryrisk-mlops/drift
  newTag: latest
replicas:
- name: deliveryrisk-api
  count: 1
- name: deliveryrisk-frontend
  count: 1
